banks:
  cibc_debit:
    sender: "mailbox.noreply@cibc.com"
    keywords: ["Achat en point de vente", "achat international"]
    regex: 
      amount: "Montant de l'achat\\s*:\\s*(\\d+[,.]\\d{2})\\s*\\$"
      description: "Lieu de l'achat\\s*:\\s*([A-Za-z0-9#&\\*\\-/ ]+)"

  cibc_credit:
    sender: "mailbox.noreply@cibc.com"
    keywords: ["Nouvel achat avec votre carte de", "paiement préautorisé avec votre carte"]
    regex:
      - amount: "achat de\\s*(\\d+[,.][0-9]{2})\\s*\\$?"
        description: "achat de\\s*\\d+[,.][0-9]{2}\\s*\\$?\\s+(?:à|a)\\s+([A-Za-z0-9.,#&\\-/ ]+?)\\s+avec votre"

      - amount: "préautorisé de\\s*([0-9]+[\\s ]?[0-9]*[,.]\\d{2})\\s*\\$"
        description: "\\$\\s+de\\s+([A-Za-z0-9.,#&\\-/ ]+?)\\s+sur votre"

  cibc_credit_refund:
    sender: "mailbox.noreply@cibc.com"
    keywords: ["remboursement porté à votre carte"]
    regex:
      amount: "crédit de\\s*([0-9]+[\\s ]?[0-9]*[,.]\\d{2})\\s*\\$"
      description: "\\$\\s+de\\s+([A-Za-z0-9.,#&\\-/ ]+?)\\s+à votre"

  cibc_interac:
    sender: "mailbox.noreply@cibc.com"
    keywords: ["Virement INTERAC"]
    regex:
      amount: "Montant\\s*:\\s*([0-9]+[\\s ]?[0-9]*[,.]\\d{2})\\s*\\$"
      description: "Nom du contact\\s*:\\s*([A-Za-z0-9éèàçÉÈÀÇ#&\\- ]+)"

  capital_one_credit:
    sender: "capitalone@notification.capitalone.com"
    keywords: ["A transaction was charged to your account", "International transaction alert"]
    exclude_keywords:
      - "Payment posted"
      - "Paiement inscrit"
      - "Thank you for your payment"
    regex:
      amount: "\\$?([0-9]+[,.][0-9]{2})\\$?"
      description: "([A-Za-z0-9#&\\- ]+)(?=\\s*\\$?[0-9]+[,.][0-9]{2}\\$?)"

  mbna_credit:
    sender: "noreply@mbna.ca"
    keywords: ["Transaction Alert", "Purchase Notification", "MBNA - Transaction Alert"]
    regex:
      amount: "\\$([0-9]+\\.[0-9]{2})"
      description: "from ([A-Za-z0-9/& ]+)"

  rbc_credit:
    sender: "alertesrbcbanqueroyale@alerts.rbc.com"
    keywords: ["Avertissement concernant une", "achat", "effectue sur votre compte"]
    exclude_keywords:
      - "paiement a ete effectue"
      - "Paiement recu"
    regex:
      amount: "achat de\\s*([0-9]+[\\s ]?[0-9]*[,.]\\d{2})\\s*\\$"
      description: "Description de l.op.ration\\s*:?\\s*\\n?\\s*([A-Za-z0-9/'#&\\*\\-\\. ]+)"

  neo_credit:
    sender: "info@neofinancial.com"
    keywords: ["You earned", "cashback on your purchase of", "Your purchase at", "You made a purchase", "Votre achat chez"]
    regex:
      - amount: "purchase of \\$([0-9]+[.,][0-9]{2}) at"
        description: "purchase of \\$[0-9]+[.,][0-9]{2} at ([A-Za-z0-9'’éèàç() \\-#&]+)"

      - amount: "purchase of \\$([0-9]+[.,][0-9]{2})"
        description: "purchase of \\$[0-9]+[.,][0-9]{2} at ([A-Za-z0-9'’éèàç() \\-#&]+)"

      - amount: "pour ([0-9]+[.,][0-9]{2}) ?\\$"
        description: "achat chez ([A-Za-z0-9'’éèàç() \\-#&]+)"



